application: hn-bayes-reader
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /images/
  static_dir: static/images

- url: /javascript/
  static_dir: static/javascript

- url: /css/
  static_dir: static/css

- url: /.*
  script: urls.py

